# Prefix Key:      Ctrl-b

# ======================= Basic Terminal Commands =======================
#
# tmux                          start new session
# tmux new -s myname            start a names session
# tmux ls                       list sessions
# tmux attach -t myname         attach to session
# tmux kill-session -t myname   kill session
#
#
# =============================== Keybinds ==============================
# Prefix: Ctrl-b
# prefix d             detach from session
# prefix c             create new window
# prefix n/p           next/prev window
# prefix 0-9           switch to window number
# prefix |             vertical split
# prefix -             horizontal split
# prefix r             source this config file
# prefix m             restore pane size
# =======================================================================

# Enables 256 colors for better visual apperance
set -g default-terminal "screen-256color"

set -g status-position top

# Minimal dark theme
set -g status-style bg=colour234,fg=colour137
set -g window-status-current-style bg=colour238,fg=colour81,bold
set -g window-status-style fg=colour138

# Remove delay when pressing esc (important for vim usage)
set -sg escape-time 0

# Default horizontal split is %, this is changed to pipe |
unbind %
bind | split-window -h

# Default vertical split is ", this is changes to pipe |
unbind '"'
bind - split-window -v

# Prefix r will source this config file
unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

# vi movements 
set-window-option -g mode-keys vi

# bind prev and next
bind-key -r '{' previous-window
bind-key -r '}' next-window

# this unbinds copying stuff with your mouse
# unbind -T copy-mode-vi MouseDragEnd1Pane

# Change movement keys to Control Shift J, Control Shift K, Control Shift H, Control Shift L
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-right "tmux config loaded"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)k
run '~/.tmux/plugins/tpm/tpm'
